<br>
<br>

<h3>Add new Auction</h3>
<form action="index.php" method="POST">
    <!-- <label for="code">Code</label>
    <input id="code" name="code" type="text">
    <br/> -->

    <label for="lotName">Lot Name</label>
    <input id="lotName" name="lotName" type="text">
    <br />

    <label for="startDate">Start Date</label>
    <input id="startDate" name="startDate" type="text">
    <br />

    <label for="finishDate">Finish Date</label>
    <input id="finishDate" name="finishDate" type="text">
    <br />

    <label for="startPrice">Start Price</label>
    <input id="startPrice" name="startPrice" type="text">
    <br />

    <label for="finalPrice">Final Price</label>
    <input id="finalPrice" name="finalPrice" type="text">
    <br />

    <button type="submit" name="submit">Submit</button>
</form>